### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by abacao** [crispe/coopernico-prices#1]
Hello @crispe 

Can you please share more detailed information about the code and what we are seeing?

The website where the data is collected (**http://coopernico.home-assistant.live/egetprices.php**) is returning at the end

```
"contador":"bi","ciclo":"semanal","current_price":0.1524}
```

How can I get the values for "Horário Simples" and "No Cicle"?

I have also tried using dropdown helpers in your code without success, do you know if that is even possible?

```
sensor:
  - platform: rest
    name: Coopernico Prices
    unique_id: coopernico_prices
    resource: http://coopernico.home-assistant.live/egetprices.php
    scan_interval: 3600
    verify_ssl: false
    unit_of_measurement: "EUR/kWh"
    params:
      ciclo: input_select.coopernico_ciclo_contagem  ## dia / semanal
      contador: input_select.coopernico_contrato  ## simples / bi / tri / tri-hp
    value_template: >
      {{value_json.current_price}}
    json_attributes:
      - Prices
      - current_price
```
